# Generated by Django 4.0.5 on 2022-06-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('appaterno', models.CharField(max_length=30)),
                ('apmaterno', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=10)),
                ('nomvacuna', models.CharField(max_length=30)),
                ('fecha', models.CharField(max_length=30)),
            ],
        ),
    ]
